### ISSUE TITLE
Upgrade terraform aws eks module to v19

### ISSUE THREAD

**Issue by thinkl33t** [finos/terraform-aws-cfi-eks#17]
We are running a couple of years old version of the terraform provider.  We are on version 17.x, 19.x is the latest 

Documentation for doing these version upgrades are available at https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-18.0.md and https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md

**Comment by eddie-knight** [comment]
Happy to implement this on our working call tomorrow morning.
