### ISSUE TITLE
Rename repo to `cfi-terraform-aws-eks`

### ISSUE THREAD

**Issue by mcleo-d** [finos/terraform-aws-cfi-eks#4]
## Description

Can this repo be renamed to `cfi-terraform-aws-eks` to ensure it's searchable and filterable under the `cfi` namespace for `Compliant Financial Infrastructure`?

Kind regards,

James.

**Comment by eddie-knight** [comment]
I don't believe we'll be able to achieve the desired functionality with the proposed name change. 

Suggest closing this issue and tagging it as invalid on the next community call.

**Comment by mcleo-d** [comment]
@eddie-knight - I've added the `invalid` label and added to `ready for review` for project call discussion and closure.

**Comment by mcleo-d** [comment]
Issue closed on https://github.com/finos/compliant-financial-infrastructure/issues/265 

For more information see https://www.terraform.io/registry/modules/publish#requirements

**Comment by thinkl33t** [comment]
To put this into the terraform repos, we need to stick with the correct nomenclature `terraform-nameofcloudprovider-freetext`, so we can't prepend with `cfi-` as initially suggested.

The current name of this module however will clash with more  generic aws eks modules in the repo.  @ml4 suggested we used `terraform-aws-cfi-eks` to distinguish from these, and build a naming convention around this style.

**Comment by eddie-knight** [comment]
Agreed, happy to apply the name change to `terraform-aws-cfi-eks`. 

@TheJuanAndOnly99, could you action the rename please?

**Comment by TheJuanAndOnly99** [comment]
@eddie-knight done! please check and close :)

**Comment by eddie-knight** [comment]
Thanks @TheJuanAndOnly99 !!
