### ISSUE TITLE
Move spin-up / teardown CI across to this repo

### ISSUE THREAD

**Issue by thinkl33t** [finos/terraform-aws-cfi-eks#9]
### Description of Problem:

We need to be running full end-to-end smoke tests of the EKS IaC on dev.

- [x] get aws keys added to this repo
- [x] move github actions from main CFI repo
- [ ] test and update as needed

**Comment by thinkl33t** [comment]
Please can someone with access to add secrets to github actions add the AWS keys that are currently on cfi - we'll be moving the CI from there that spins up and destroys the cluster into this repo.

Pinging @maoo and @TheJuanAndOnly99 as i believe they're the people with the keys :)

**Comment by maoo** [comment]
> Pinging @maoo and @TheJuanAndOnly99 as i believe they're the people with the keys :)

Hi, I'm one the people with the keys 😄 

I've added `AWS_KEY_ID` and `AWS_KEY_SECRET` secrets on the `csc-eks` user (already used for other EKS deployment); sadly we didn't store the secret of the previous key, so we had to create a new one.

Please let me know if you encouter any issue!

**Comment by thinkl33t** [comment]
Fantastic, thanks @maoo

**Comment by thinkl33t** [comment]
https://github.com/finos/terraform-aws-cfi-eks/pull/11 has the CI for performing a teardown / buildup cycle.

**Comment by eddie-knight** [comment]
Reviving this after discussion on the RI WG call today, Bob will need to revisit the PR to get it up to date with the latest Actions functionality & figure out any other pending issues.
